language: php
cache: false

sudo: false

php:
  - 7.1
  - nightly

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - php -n ./vendor/bin/phpbench run --revs=1000 --iterations=10 --warmup=2 --report=aggregate
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./test/ ./benchmark/
  - ./vendor/bin/humbug

matrix:
  allow_failures:
    - php: nightly
